exclude: "^.venv/.*|.html"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: pretty-format-json
      args: ["--autofix"]
    - id: check-merge-conflict
  - repo: local
    hooks:
    - id: lockfile
      name: check poetry.lock
      language: system
      entry: poetry lock --no-update
      files: ^pyproject.toml|poetry.lock$
      pass_filenames: false
    - id: isort
      name: isort
      language: system
      entry: poetry run isort microbatcher tests
      types: [python]
      pass_filenames: false
    - id: blacken
      name: blacken
      language: system
      entry: poetry run black microbatcher tests
      types: [python]
      pass_filenames: false
    - id: flake8
      name: flake8
      language: system
      entry: poetry run flake8 microbatcher tests
      types: [python]
    - id: pyright
      name: pyright
      language: system
      entry: poetry run pyright microbatcher tests
      types: [python]
      pass_filenames: false